#pragma config(StandardModel, "RVW Fantasticbot")
#pragma config(RenamedStdModelSensor, I2C_1, rightEncoder)
#pragma config(RenamedStdModelSensor, I2C_2, leftEncoder)
#pragma config(RenamedStdModelSensor, I2C_3, armEncoder)
#pragma config(RenamedStdModelSensor, I2C_4, extensionEncoder)
#pragma config(RenamedStdModelSensor, I2C_5, wristEncoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//This function moves the arm motor based off of a certain amount of time
void moveArmForTime(int armPower, int time)
{
	motor[armMotor] = armPower;//move arm at certain power
	wait1Msec(time);//move arm for a certain time
}

//This function moves the wrist up until the encoder reaches a certain amount
void moveArmForRotationsUp(int armEncoderPower, int rotations)
{
	SensorValue[armEncoder] = 0;//Resets the encoder value on the arm
	while(SensorValue[armEncoder] < rotations)
		{
			motor[armMotor] = armEncoderPower;//Move the wrist at a certain speed
		}
	motor[armMotor] = 0;//Stop the arm
}

//This function moves the arm down until the encoder reaches a certain amount
void moveArmForRotationsDown(int armEncoderPowerRev, int negativeRotations)
{
	SensorValue[armEncoder] = 0;//Resets the encoder value on the arm
	while(SensorValue[armEncoder] > -negativeRotations)
		{
			motor[armMotor] = -armEncoderPowerRev;//Move the arm at a certain speed
		}
	motor[armMotor] = 0;//Stop the arm
}
