#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    leftLight,      sensorLineFollower)
#pragma config(Sensor, in2,    middleLight,    sensorLineFollower)
#pragma config(Sensor, in3,    rightLight,     sensorLineFollower)
#pragma config(Sensor, in4,    wristPot,       sensorPotentiometer)
#pragma config(Sensor, in6,    gyro,           sensorGyro)
#pragma config(Sensor, dgtl7,  touchSensor,    sensorTouch)
#pragma config(Sensor, dgtl8,  sonarSensor,    sensorSONAR_cm)
#pragma config(Sensor, I2C_1,  rightEncoder,   sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  leftEncoder,    sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_3,  armEncoder,     sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_4,  extensionEncoder, sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_5,  wristEncoder,   sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           frontRightMotor, tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           rearRightMotor, tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_1)
#pragma config(Motor,  port3,           frontLeftMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           rearLeftMotor, tmotorVex393_MC29, openLoop, encoderPort, I2C_2)
#pragma config(Motor,  port6,           clawMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           armMotor,      tmotorVex393_MC29, openLoop, encoderPort, I2C_3)
#pragma config(Motor,  port8,           leftExtendMotor, tmotorVex393_MC29, openLoop, encoderPort, I2C_4)
#pragma config(Motor,  port9,           rightExtendMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          wristMotor,    tmotorVex393_HBridge, openLoop, encoderPort, I2C_5)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


//Date Modified: 26 October 2016


/*
This code is included in all of the files starting with "Main_File_Draft_..."
It consists of all of the functions for the arm that are needed to run
the fantasticbot properly. These functions are (in order):
- moveArmForTime
- moveArmForRotationsUp
- moveArmForRotationsDown
NOTE: The approximate maximum value for the arm encoder is around 875
NOTE: The approximate minimum value for the arm encoder is around 0
NOTE: Any function that has to do with the encoders on the arm (has "Rotations" in the name)
is currently under maintenance. The encoders will not reset properly (still used in main code).
*/


//This function moves the arm motor for a  speed and an amount of time -------------------------------------------------------------------------
void moveArmForTime(int armPower, int time) //Power to the arm, time arm moves
{
	motor[armMotor] = armPower; //Move arm at certain power
	wait1Msec(time); //Move arm for a certain time
}


//This function moves the wrist up until the encoder reaches a certain amount ------------------------------------------------------------------
void moveArmForRotationsUp(int armEncoderPower, int rotations) //Power to the arm, distance arm moves with encoders
{
	while(SensorValue[armEncoder] < rotations) //While arm encoder value is less than desired value
	{
		motor[armMotor] = armEncoderPower; //Move the arm at a certain speed up
	}
	motor[armMotor] = 0; //Stop the arm
}


//This function moves the arm down at a certain speed until the encoder reaches a certain amount -----------------------------------------------
void moveArmForRotationsDown(int armEncoderPowerReversed, int negativeRotations) //Power to the arm, distance arm moves with encoders
{
	while(SensorValue[armEncoder] > -negativeRotations) //While arm encoder value is less than desired value
	{
		motor[armMotor] = -armEncoderPowerReversed; //Move the arm at a certain speed down
	}
	motor[armMotor] = 0; //Stop the arm
}
