#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    leftLight,      sensorLineFollower)
#pragma config(Sensor, in2,    middleLight,    sensorLineFollower)
#pragma config(Sensor, in3,    rightLight,     sensorLineFollower)
#pragma config(Sensor, in4,    wristPot,       sensorPotentiometer)
#pragma config(Sensor, in6,    gyro,           sensorGyro)
#pragma config(Sensor, dgtl7,  touchSensor,    sensorTouch)
#pragma config(Sensor, dgtl8,  sonarSensor,    sensorSONAR_cm)
#pragma config(Sensor, I2C_1,  rightEncoder,   sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  leftEncoder,    sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_3,  armEncoder,     sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_4,  extensionEncoder, sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_5,  wristEncoder,   sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           frontRightMotor, tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           rearRightMotor, tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_1)
#pragma config(Motor,  port3,           frontLeftMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           rearLeftMotor, tmotorVex393_MC29, openLoop, encoderPort, I2C_2)
#pragma config(Motor,  port6,           clawMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           armMotor,      tmotorVex393_MC29, openLoop, encoderPort, I2C_3)
#pragma config(Motor,  port8,           leftExtendMotor, tmotorVex393_MC29, openLoop, encoderPort, I2C_4)
#pragma config(Motor,  port9,           rightExtendMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          wristMotor,    tmotorVex393_HBridge, openLoop, encoderPort, I2C_5)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int topdistance = 902; //Highest distance the encoder on the extension can read
int halfdistance = 451; //Middle distance the encoder on the extension can read
int bottomdistance = 0; //Lowest distance the encoder on the extension can read


//This function uses the extension and moves it for time ---------------------------------------------------------------------------------------
void moveExtensionForTime(int speed, float time)
{
	motor[leftExtendMotor] = speed; //extends arm
	motor[rightExtendMotor] = speed;
	wait1Msec(time*1000); //time spent extending arm
	motor[leftExtendMotor] = 0; //stops the extension
	motor[rightExtendMotor] = 0;
}


//This function uses the extension and moves it up for distance --------------------------------------------------------------------------------
void moveExtensionUpForDistance(int speedup, int distanceup)
{
	SensorValue[extensionEncoder] = 0;
	while(SensorValue[extensionEncoder] < distanceup) //extending arm until distance
	{
		motor[leftExtendMotor] = speedup; //extends arm
		motor[rightExtendMotor] = speedup;
	}
	motor[leftExtendMotor] = 0; //stops the extension
	motor[rightExtendMotor] = 0;
}


//This function uses the extension and moves it down for distance ------------------------------------------------------------------------------
void moveExtensionDownForDistance(int speeddown, int distancedown)
{
	SensorValue[extensionEncoder] = 0;
	while(SensorValue[extensionEncoder] > distancedown) //extending arm until distance
	{
		motor[leftExtendMotor] = -speeddown; //extends arm
		motor[rightExtendMotor] = -speeddown;
	}
	motor[leftExtendMotor] = 0; //stops the extension
	motor[rightExtendMotor] = 0;
}
