#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    leftLight,      sensorLineFollower)
#pragma config(Sensor, in2,    middleLight,    sensorLineFollower)
#pragma config(Sensor, in3,    rightLight,     sensorLineFollower)
#pragma config(Sensor, in4,    wristPot,       sensorPotentiometer)
#pragma config(Sensor, in6,    gyro,           sensorGyro)
#pragma config(Sensor, dgtl7,  touchSensor,    sensorTouch)
#pragma config(Sensor, dgtl8,  sonarSensor,    sensorSONAR_cm)
#pragma config(Sensor, I2C_1,  rightEncoder,   sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  leftEncoder,    sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_3,  armEncoder,     sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_4,  extensionEncoder, sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_5,  wristEncoder,   sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           frontRightMotor, tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           rearRightMotor, tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_1)
#pragma config(Motor,  port3,           frontLeftMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           rearLeftMotor, tmotorVex393_MC29, openLoop, encoderPort, I2C_2)
#pragma config(Motor,  port6,           clawMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           armMotor,      tmotorVex393_MC29, openLoop, encoderPort, I2C_3)
#pragma config(Motor,  port8,           leftExtendMotor, tmotorVex393_MC29, openLoop, encoderPort, I2C_4)
#pragma config(Motor,  port9,           rightExtendMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          wristMotor,    tmotorVex393_HBridge, openLoop, encoderPort, I2C_5)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


//Date Modified: 29 November 2016


/*
This file is the seventh draft of the Starstruck RVW Online Challenge.
NOTE: When using time, it is already converted to seconds instead of milliseconds.
See files included for more information.
NOTE: When using degrees, it is already converted to actual degrees instead
of degrees*10. See "Base.c" for more information.
*/


#include "Arm.c" //This includes all of the functions that involve the arm
#include "Base.c" //This includes all of the functions that involve the base
#include "Claw.c" //This includes all of the functions that involve the claw
#include "Extension.c" //This includes all of the functions that involve the extension
#include "Wrist.c" //This inclues all of the functions that involve the extension
#include "Multiple_Parts.c" //This includes all functions that involve multiple subsystems


/*
This program is organized by points and actions oriented with
stars and cubes. Each section scores points and completes
actions in some way, shape, or form. See the far right of the
screen for details of actions and points scored (theoretically,
of course). Keep in mind that all of this is subject to change
and may not work when tried out on robot virtual worlds.
NOTE: When the comments say things like "top left corner"
look down at the field from side robot is starting on.
*/


task main()
{
	moveBaseArmAndWrist(127, 120, 127, -60, 1);
	moveBaseForTime(127, 127, 1.9);
	moveBaseArmAndClaw(-127, -127, -30, openclaw, 1);
	moveBaseArmAndWrist(-127, -127, -127, 60, 1.7);

	/*Summary: Robot drives forward with a cube in claw,
	lifts arm and knocks a cube
	off the wall then drops cube in claw
	Proceeds to then  back up to start*/

	//2 points scored

	turnLeftWithGyro(127, -82);
	moveBaseForTime(127, 127, 1);
	moveClawForTime(closeclaw);
	turnRightWithGyro(127, -6.5);
	moveBaseArmAndWrist(127, 127, 127, -127, 1.2);
	moveBaseForTime(127, 127, 1.9);
	moveBaseForTime(-127, -127, 0.2);
	moveBaseForTime(-25, -127, 0.75);
	moveBaseForTime(127, 127, 0.7);
	turnLeftWithGyro(127, 2);
	moveBaseArmClawAndWrist(-127, -127, -25, openclaw, 100, 1.85);
	moveArmForRotationsDown(127, 1);

	/*Summary: Robot spins left and grabs a star,
	drives towards wall while pushing one cube under the wall and
	two other over, Robot then drives back to start*/

	//4 pts scored
	//**Total: 6 points


	turnRightWithGyro(127, 85);
	moveBaseForTime(127, 127, 2);
	moveBaseArmExtensionClawAndWrist(-40, 127, 112, 95, closeclaw, -79, 1);
	turnLeftWithGyro(127, 0);
	turnRightWithGyro(127, 45);
	moveBaseAndArm(127, 127, 15, 1.5);
	turnLeftWithGyro(127, 0);

	/*Summary: Turns right and drives towards center cube,
	grabs cube then knocks four stars off the center wall,
	then reverses and turns left*/

	//4 points scored
	//**Total: 10 points (Possible 11 points is accidental)


	moveBaseForTime(-127, -127, 0.8);
	turnRightWithGyro(127, 80);
	moveBaseForTime(127, 127, 1.7);
	turnLeftWithGyro(127, 0);
	moveBaseForTime(127, 127, 1.2);
	moveClawForRotationsUp(127, -460);
	moveBaseArmExtensionClawAndWrist(-127, -127, 40, -127, openclaw, 55, 1.5);

	/*Summary: Move to Right side of the field with the cube
	Turn right towards right wall and knock stars off
	Claw then releases cube over wall*/

	//4 pts scored
	//Total: 14 points


	moveBaseAndArm(80, -80, -127, 1.2);
	turnRightWithGyro(127, 130);
	moveBaseForTime(127, 127, 1);
	moveClawForTime(closeclaw);
	turnRightWithGyro(127, 176);
	moveBaseAndArm(-127, -127, 127, 1.5);
	moveBaseForTime(-127, -127, 0.5);
	moveBaseArmAndClaw(127, 60, -127, openclaw, 2.5);

	/*Summary: Grabs far right corner star
	drives backward towards right wall while pushing stars under wall
	drops star over wall and scores*/

	//scores 3 pts
	//**Total: 17 pts


	moveBaseForTime(127, 127, 0.9);
	turnLeftWithGyro(127, 210);
	moveBaseForTime(127, 127, 0.8);
	moveBaseArmAndClaw(-127, -100, 127, closeclaw, 1.5);
	moveBaseAndArm(-127, -127, 60, 0.8);
	moveBaseArmAndClaw(127, 127, -127, openclaw, 2);

	/**/
}
