#pragma config(StandardModel, "RVW Fantasticbot")
#pragma config(RenamedStdModelSensor, I2C_1, rightEncoder)
#pragma config(RenamedStdModelSensor, I2C_2, leftEncoder)
#pragma config(RenamedStdModelSensor, I2C_3, armEncoder)
#pragma config(RenamedStdModelSensor, I2C_4, extensionEncoder)
#pragma config(RenamedStdModelSensor, I2C_5, wristEncoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "Arm.c"
#include "Base.c"
#include "Claw.c"
#include "Extension.c"
#include "Wrist.c"

task main()
{
	stopAtLine(127);
	moveBaseForTime(-127, 127, 1.45 );
	moveArmForRotationsUp(127, 775);
	moveBaseForTime(-127, -127, 1.75);
	moveClawForTime(openclaw); //score first star
	moveArmForRotationsDown(127, 1);
	moveBaseForTime(127, 127, 0.15);
	moveBaseForTime(127, -127, 0.75);
	moveBaseForTime(127, 127, 1.25); //move to second star
	moveClawForTime(closeclaw);
	moveBaseForTime(-127, 127, 0.725);
	moveArmForRotationsUp(127, 780);
	//moveBaseForTime(-127, -127, 0.15);
	moveClawForTime(openclaw); //score second star
	moveArmForRotationsDown(127, 1);
	//moveBaseForTime(127, 127, 0.15);
	moveBaseForTime(127, 127, 0.15);
	moveBaseForTime(-127, 127, 0.715);
	moveBaseForTime(127, 127, 2.6); //move to third star
	moveClawForTime(closeclaw);
	moveBaseForTime(127, -127, 0.725);
	moveArmForRotationsUp(127, 775);
	moveBaseForTime(-127, -127, 0.15);
	moveClawForTime(openclaw); //score third star
	moveArmForRotationsDown(127, 1);
	moveBaseForTime(127, 127, 0.15);
	moveBaseForTime(-127, 127, 0.720);
	moveBaseForTime(127, 127, 1.4); //move to fourth star
	moveClawForTime(closeclaw);
	moveBaseForTime(-127, -127, 0.15);
	moveBaseForTime(127, -127, 0.7);
	moveBaseForTime(-127, -127, 0.15);
	moveArmForRotationsUp(127, 775);
	moveClawForTime(openclaw); //score fourth star
	moveArmForRotationsDown(127, 1);
	moveBaseForTime(127, 127, 0.15);
	moveBaseForTime(-127, 127, 0.7);
	moveBaseForTime(127, 127, 1.25); //move to fifth star
	moveClawForTime(closeclaw);
	moveBaseForTime(127, -127, 0.7);
	moveArmForRotationsUp(127, 775);
	moveBaseForTime(-127, -127, 0.3);
	moveClawForTime(openclaw); //score fifth star
	moveArmForRotationsDown(127, 1);
	moveBaseForTime(127, 127, 0.2);
	moveBaseForTime(-127, 127, 0.7);
	moveBaseForTime(127, 127, 1.25); //move to sixth star
	moveClawForTime(closeclaw);
	moveBaseForTime(127, -127, 0.7);
	moveBaseForTime(-127, -127, 0.3);
	moveArmForRotationsUp(127, 775);
	moveClawForTime(openclaw); //score sixth star
	moveArmForRotationsDown(127, 1);
	moveBaseForTime(127, -127, 0.15);
	moveBaseForTime(127, 127, 2.2); //move to first cube
	moveClawForTime(closeclaw);
	moveBaseForTime(-127, 127, 0.15);
	moveBaseForTime(-127, -127, 1.9);
	moveArmForRotationsUp(127, 775);
	moveClawForTime(openclaw); //score first cube
	moveArmForRotationsDown(127, 1);
	moveBaseForTime(127, -127, 0.4);
	moveBaseForTime(127, 127, 2.5); //move to second cube
	moveClawForTime(closeclaw);
	moveBaseForTime(-127, 127, 0.3);
	moveBaseForTime(-127, -127, 1.2);
	moveArmForRotationsUp(127, 775);
	moveClawForTime(openclaw); //score second cube

}
