#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    leftLight,      sensorLineFollower)
#pragma config(Sensor, in2,    middleLight,    sensorLineFollower)
#pragma config(Sensor, in3,    rightLight,     sensorLineFollower)
#pragma config(Sensor, in4,    wristPot,       sensorPotentiometer)
#pragma config(Sensor, in6,    gyro,           sensorGyro)
#pragma config(Sensor, dgtl7,  touchSensor,    sensorTouch)
#pragma config(Sensor, dgtl8,  sonarSensor,    sensorSONAR_cm)
#pragma config(Sensor, I2C_1,  rightEncoder,   sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  leftEncoder,    sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_3,  armEncoder,     sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_4,  extensionEncoder, sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_5,  wristEncoder,   sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           frontRightMotor, tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           rearRightMotor, tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_1)
#pragma config(Motor,  port3,           frontLeftMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           rearLeftMotor, tmotorVex393_MC29, openLoop, encoderPort, I2C_2)
#pragma config(Motor,  port6,           clawMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           armMotor,      tmotorVex393_MC29, openLoop, encoderPort, I2C_3)
#pragma config(Motor,  port8,           leftExtendMotor, tmotorVex393_MC29, openLoop, encoderPort, I2C_4)
#pragma config(Motor,  port9,           rightExtendMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          wristMotor,    tmotorVex393_HBridge, openLoop, encoderPort, I2C_5)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


//Date Modified: 17 November 2016


/*
This file is the seventh draft of the Starstruck RVW Online Challenge.
NOTE: When using time, it is already converted to seconds instead of milliseconds.
See files included for more information.
NOTE: When using degrees, it is already converted to actual degrees instead
of degrees*10. See "Base.c" for more information.
*/


#include "Arm.c" //This includes all of the functions that involve the arm
#include "Base.c" //This includes all of the functions that involve the base
#include "Claw.c" //This includes all of the functions that involve the claw
#include "Extension.c" //This includes all of the functions that involve the extension
#include "Wrist.c" //This inclues all of the functions that involve the extension
#include "Multiple_Parts.c" //This includes all functions that involve multiple subsystems


/*
This program is organized by points and actions oriented with
stars and cubes. Each section scores points and completes
actions in some way, shape, or form. See the far right of the
screen for details of actions and points scored (theoretically,
of course). Keep in mind that all of this is subject to change
and may not work when tried out on robot virtual worlds.
NOTE: When the comments say things like "top left corner"
look down at the field from side robot is starting on.
*/


task main()
{
	moveBaseArmAndWrist(127, 120, 127, -60, 1);
	moveBaseForTime(127, 127, 1.9);
	moveBaseArmAndClaw(-127, -127, -30, openclaw, 1);
	moveBaseArmAndWrist(-127, -127, -127, 60, 1.7);
	turnLeftWithGyro(127, -82);
	moveBaseForTime(127, 127, 0.5);
	moveClawForTime(closeclaw);
	turnRightWithGyro(127, -5);
	moveBaseForTime(127, 127, 2.95);
	moveBaseAndClaw(-127, -127, openclaw, 1.65);


	turnRightWithGyro(127, 87);
	moveBaseForTime(127, 127, 2.1);
	moveBaseAndClaw(127, 127, closeclaw, 2.7);
	moveBaseForTime(-70, 127, 1.1);
	moveBaseArmAndWrist(-40, -40, 127, -90, 1);
	moveBaseForTime(127, 127, 1);
	moveBaseForTime(-127, -127, 0.8);


	turnLeftWithGyro(127, -85);
	moveBaseAndArm(127, 127, -80, 0.1);
	moveBaseForTime(127, 127, 2.1);
	turnRightWithGyro(127, 0);
	moveBaseForTime(127, 127, 1);
	wait1Msec(700);
	moveBaseForTime(-127, -127, 0.6);


	turnLeftWithGyro(127, -85);
	moveBaseAndArm(127, 127, 85, 0.1);
	moveBaseForTime(127, 127, 2.7);
	turnRightWithGyro(127, 0);
	moveBaseForTime(127, 127, 1.2);
	moveBaseArmAndClaw(-127, -127, -30, openclaw, 1.5);
	moveArmAndWrist(-80, 110, 1);
	moveArmForRotationsDown(127, 1);


	turnRightWithGyro(127, 88);
	moveBaseForTime(127, 127, 4);
	turnRightWithGyro(127, 125);
	moveBaseForTime(127, 127, 1);
	moveBaseArmAndClaw(-85, 87, 127, closeclaw, 1.2);
	moveBaseAndWrist(127, 127, -127, 1.1);
	moveBaseForTime(127, 127, 1.8);
	moveBaseForTime(-127, 127, 0.5);
	moveBaseForTime(127, 127, 0.2);
	moveExtensionUpForDistance(127, 500);
	moveBaseArmAndClaw(-127, -127, -60, openclaw, 1);
	moveExtensionDownForDistance(127, 1);
	moveArmAndWrist(-30, 127, 1.1);
	moveArmForRotationsDown(127, 1);


	turnRightWithGyro(127, 172);
	moveBaseForTime(127, 127, 1.3);
	moveBaseArmAndClaw(-127, -127, 127, closeclaw, 1.5);
	moveBaseForTime(-127, -127, 0.4);
	moveClawForTime(openclaw);
}
