#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    leftLight,      sensorLineFollower)
#pragma config(Sensor, in2,    middleLight,    sensorLineFollower)
#pragma config(Sensor, in3,    rightLight,     sensorLineFollower)
#pragma config(Sensor, in4,    wristPot,       sensorPotentiometer)
#pragma config(Sensor, in6,    gyro,           sensorGyro)
#pragma config(Sensor, dgtl7,  touchSensor,    sensorTouch)
#pragma config(Sensor, dgtl8,  sonarSensor,    sensorSONAR_cm)
#pragma config(Sensor, I2C_1,  rightEncoder,   sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  leftEncoder,    sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_3,  armEncoder,     sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_4,  extensionEncoder, sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_5,  wristEncoder,   sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           frontRightMotor, tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           rearRightMotor, tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_1)
#pragma config(Motor,  port3,           frontLeftMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           rearLeftMotor, tmotorVex393_MC29, openLoop, encoderPort, I2C_2)
#pragma config(Motor,  port6,           clawMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           armMotor,      tmotorVex393_MC29, openLoop, encoderPort, I2C_3)
#pragma config(Motor,  port8,           leftExtendMotor, tmotorVex393_MC29, openLoop, encoderPort, I2C_4)
#pragma config(Motor,  port9,           rightExtendMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          wristMotor,    tmotorVex393_HBridge, openLoop, encoderPort, I2C_5)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#include "Arm.c"
#include "Base.c"
#include "Claw.c"
#include "Extension.c"
#include "Wrist.c"
task main()
{
	stopAtLine(127);
	turnRightWithGyro(127, 172);
	moveBaseForTime(-127, -127, 1.9);
	moveArmForRotationsUp(127, 700); //Knock stars over the fence
	moveClawForTime(openclaw); //Score first held star over the fence
	moveBaseForTime(127, 127, 0.8);
	turnRightWithGyro(127, 267);
	moveArmForRotationsDown(127, 0);
	moveBaseForTime(127, 127, 0.5);
	moveClawForTime(closeclaw); //Grab star farthest towards west wall
	moveBaseForTime(-127, -127, 2.8);
	turnLeftWithGyro(127, 187);
	moveBaseForTime(127, 127, 0.2);
	moveArmForRotationsUp(127, 875);
	moveBaseForTime(-127, -127, 0.4); //Knock stars over the fence
	moveClawForTime(openclaw); //Score star over the fence
	moveArmForRotationsDown(127, 0);
	turnLeftWithGyro(127, 155);
	moveBaseForTime(127, 127, 1);
	moveClawForTime(closeclaw); //Grab cube in the middle of the field
	moveBaseForTime(-127, -127, 0.8);
	turnRightWithGyro(127, 165);
	moveArmForRotationsUp(127, 700);
	moveExtensionUpForDistance(127, 900);
	moveArmForRotationsUp(127, 875);
	moveBaseForTime(-127, -127, 0.5);
	moveClawForTime(openclaw); //Score first held cube over the fence
	moveBaseForTime(127, 127, 1);
	moveExtensionDownForDistance(127, 0);
	moveArmForRotationsDown(127, 0);
	turnLeftWithGyro(127, 88);
	moveBaseForTime(127, 127, 2.7);
	moveClawForTime(closeclaw); //Grab star farthest towards east wall
	turnRightWithGyro(127, 185);
	moveArmForRotationsUp(127, 800);
	moveBaseForTime(-127, -127, 0.3);
	moveClawForTime(openclaw); //Score star over the fence
	moveArmForRotationsDown(127, 0);
	turnRightWithGyro(127, 195);
	moveBaseForTime(127, 127, 2);
	moveClawForTime(closeclaw); //Grab cube along wall farthest from midline
	moveBaseForTime(-127, -127, 1.8);
	moveArmForRotationsUp(127, 700);
	moveExtensionUpForDistance(127, 900);
	moveArmForRotationsUp(127, 850);
	turnLeftWithGyro(127, 180);
	moveBaseForTime(-127, -127, 0.5);
	moveClawForTime(openclaw); //Score cube over the fence
	moveBaseForTime(127, 127, 1.5);
	moveExtensionDownForDistance(127, 0);
	moveArmForRotationsDown(127, 0);
	turnLeftWithGyro(127, 168);
	moveBaseForTime(127, 127, 1.8);
	moveClawForTime(closeclaw); //Grab star in furthest corner from star along same wall
	moveBaseForTime(-127, -127, 2.3);
	moveArmForRotationsUp(127, 700);
	moveClawForTime(openclaw); //Score star over the fence
}
