#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    leftLight,      sensorLineFollower)
#pragma config(Sensor, in2,    middleLight,    sensorLineFollower)
#pragma config(Sensor, in3,    rightLight,     sensorLineFollower)
#pragma config(Sensor, in4,    wristPot,       sensorPotentiometer)
#pragma config(Sensor, in6,    gyro,           sensorGyro)
#pragma config(Sensor, dgtl7,  touchSensor,    sensorTouch)
#pragma config(Sensor, dgtl8,  sonarSensor,    sensorSONAR_cm)
#pragma config(Sensor, I2C_1,  rightEncoder,   sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  leftEncoder,    sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_3,  armEncoder,     sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_4,  extensionEncoder, sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_5,  wristEncoder,   sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           frontRightMotor, tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           rearRightMotor, tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_1)
#pragma config(Motor,  port3,           frontLeftMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           rearLeftMotor, tmotorVex393_MC29, openLoop, encoderPort, I2C_2)
#pragma config(Motor,  port6,           clawMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           armMotor,      tmotorVex393_MC29, openLoop, encoderPort, I2C_3)
#pragma config(Motor,  port8,           leftExtendMotor, tmotorVex393_MC29, openLoop, encoderPort, I2C_4)
#pragma config(Motor,  port9,           rightExtendMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          wristMotor,    tmotorVex393_HBridge, openLoop, encoderPort, I2C_5)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#include "Arm.c"
#include "Base.c"
#include "Claw.c"
#include "Extension.c"
#include "Wrist.c"
task main()
{
	stopAtLine(127);
	turnRightWithGyro(127, 172);
	moveBaseForTime(-127, -127, 1.9);
	moveArmForRotationsUp(127, 700); //Knock stars over the fence
	moveClawForTime(openclaw); //Score first held star over the fence
	moveArmForRotationsDown(127, 1);
	stopAtLine(127);
	turnLeftWithGyro(127, 100);
	moveBaseForTime(127, 127, 1.6);
	moveClawForTime(closeclaw); //Grab cube in the middle of the field
	moveArmForRotationsUp(127, 800);
	turnRightWithGyro(127, 180);
	moveExtensionUpForDistance(127, 290);
	moveBaseForTime(-127, -127, 1);
	moveExtensionUpForDistance(127, 700);
	wait1Msec(1000);
	moveBaseForTime(127, 127, 1.05);
	turnLeftWithGyro(127, 92);
	moveBaseForTime(127, 127, 1.5);
	moveExtensionDownForDistance(127, 350);
	turnRightWithGyro(127, 175);
	moveBaseForTime(-127, -127, 1.4);
	moveExtensionUpForDistance(127, 900);
	moveClawForTime(openclaw); //Score cube over the fence
	moveExtensionDownForDistance(127, 0);
	moveArmForRotationsDown(127, 1);
	moveBaseForTime(127, 127, 0.7);
	turnLeftWithGyro(127, 87);
	moveBaseForTime(127, 127, 2.2);
	moveClawForTime(closeclaw); //Grab star farthest from start
	moveBaseForTime(-127, -127, 0.3);
	turnRightWithGyro(127, 170);
	moveBaseForTime(-127, -127, 0.65);
	moveArmForRotationsUp(127, 400);
	moveExtensionUpForDistance(127, 300);
	moveArmForRotationsUp(127, 750);
	moveClawForTime(openclaw); //Score star over the fence
	moveBaseForTime(127, 127, 0.5);
	moveExtensionDownForDistance(127, 0);
	moveArmForRotationsDown(127, 1);
	turnRightWithGyro(127, 185);
	moveBaseForTime(127, 127, 1.5);
	moveClawForTime(closeclaw); //Grab cube in other starting position
	turnLeftWithGyro(127, 175);
	moveBaseForTime(-127, -127, 2.05);
	moveArmForRotationsUp(127, 500);
	moveExtensionUpForDistance(127, 500);
	moveArmForRotationsUp(127, 750);
	moveClawForTime(openclaw); //Score cube over the fence
	moveExtensionDownForDistance(127, 0);
	moveArmForRotationsDown(127, 1);
	turnRightWithGyro(127, 280);
	moveBaseForTime(127, 127, 0.6);
	moveClawForTime(closeclaw); //Grab star closest to robot's current position
	turnLeftWithGyro(127, 180);
	moveArmForRotationsUp(127, 750);
	moveClawForTime(openclaw); //Score star over the fence
	moveArmForRotationsDown(127, 1);
	turnRightWithGyro(127, 200);
	moveBaseForTime(127, 127, 2);
	moveClawForTime(closeclaw); //Grab star in middle near wall
	turnLeftWithGyro(127, 180);
	moveBaseForTime(-127, -127, 2);
	moveArmForRotationsUp(127, 500);
	moveExtensionUpForDistance(127, 400);
	moveArmForRotationsUp(127, 750);
	moveClawForTime(openclaw); //Score star over the fence
}
