#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    leftLight,      sensorLineFollower)
#pragma config(Sensor, in2,    middleLight,    sensorLineFollower)
#pragma config(Sensor, in3,    rightLight,     sensorLineFollower)
#pragma config(Sensor, in4,    wristPot,       sensorPotentiometer)
#pragma config(Sensor, in6,    gyro,           sensorGyro)
#pragma config(Sensor, dgtl7,  touchSensor,    sensorTouch)
#pragma config(Sensor, dgtl8,  sonarSensor,    sensorSONAR_cm)
#pragma config(Sensor, I2C_1,  rightEncoder,   sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  leftEncoder,    sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_3,  armEncoder,     sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_4,  extensionEncoder, sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_5,  wristEncoder,   sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           frontRightMotor, tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           rearRightMotor, tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_1)
#pragma config(Motor,  port3,           frontLeftMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           rearLeftMotor, tmotorVex393_MC29, openLoop, encoderPort, I2C_2)
#pragma config(Motor,  port6,           clawMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           armMotor,      tmotorVex393_MC29, openLoop, encoderPort, I2C_3)
#pragma config(Motor,  port8,           leftExtendMotor, tmotorVex393_MC29, openLoop, encoderPort, I2C_4)
#pragma config(Motor,  port9,           rightExtendMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          wristMotor,    tmotorVex393_HBridge, openLoop, encoderPort, I2C_5)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


//Date Modified: 18 November 2016


/*
This code is included in all of the files starting with "Main_File_Draft_..."
It consists of all of the functions for multiple parts at once that are needed
to run the fantasticbot properly. These functions are (in order):
- moveBaseAndArm
- moveBaseAndClaw
- moveArmAndClaw
- moveBaseArmAndClaw
- moveBaseAndExtension
- moveArmAndWrist
- moveBaseAndWrist
- moveBaseArmAndWrist
- moveBaseArmClawAndWrist
- moveBaseExtensionAndClaw
- moveBaseArmExtensionClawAndWrist
- moveBaseArmAndExtension
- moveBaseExtensionAndClaw
*/


//This function moves the arm and the base at the same time at a certain speed for a certain amount of time ------------------------------------
void moveBaseAndArm(int baseleftspeed, int baserightspeed, int armspeed, float time) //Left side of base, right side of base, arm, time
{
	motor[frontLeftMotor] = baseleftspeed;
	motor[frontRightMotor] = baserightspeed;
	motor[rearLeftMotor] = baseleftspeed;
	motor[rearRightMotor] = baserightspeed; //Move base at a certain speed
	motor[armMotor] = armspeed; //Move arm at a certain speed
	wait1Msec(time*1000); //Wait for a certain amount of time
	motor[frontLeftMotor] = 0;
	motor[frontRightMotor] = 0;
	motor[rearLeftMotor] = 0;
	motor[rearRightMotor] = 0;
	motor[armMotor] = 0; //Turn all subsystems in function off
}

//This function moves the base and the claw at the same time at a certain speed for a certain amount of time ------------------------------------
void moveBaseAndClaw(int baseleftspeed2, int baserightspeed2, int clawdirection, float time2) //Left side of base, right side of base, claw, time
{
	motor[frontLeftMotor] = baseleftspeed2;
	motor[frontRightMotor] = baserightspeed2;
	motor[rearLeftMotor] = baseleftspeed2;
	motor[rearRightMotor] = baserightspeed2; //Move base at a certain speed
	motor[clawMotor] = -127*clawdirection; //Move claw at a ceratin speed
	wait1Msec(time2*1000); //Wait for a ceratin amount of time
	motor[frontLeftMotor] = 0;
	motor[frontRightMotor] = 0;
	motor[rearLeftMotor] = 0;
	motor[rearRightMotor] = 0;
	motor[clawMotor] = 0; //Turn all subsystems in function off
}

//This function moves the arm and the claw at the same time at a certain speed for a certain amount of time ------------------------------------
void moveArmAndClaw(int armspeed2, int clawdirection2, float time3) //Arm, claw, time
{
	motor[armMotor] = armspeed2; //Move arm at a certain speed
	motor[clawMotor] = -127*clawdirection2; //Move claw at a certain speed
	wait1Msec(time3*1000); //Wait for a certain amount of time
	motor[armMotor] = 0;
	motor[clawMotor] = 0; //Turn all subsystems in function off
}

//This function moves the base, arm, and claw at the same time at a ceratin speed for a certain amount of time ----------------------------------------------------------
void moveBaseArmAndClaw(int baseleftspeed3, int baserightspeed3, int armspeed3, int clawdirection3, float time4) //Left side of base, right side of base, arm, claw, time
{
	motor[frontLeftMotor] = baseleftspeed3;
	motor[rearLeftMotor] = baseleftspeed3;
	motor[frontRightMotor] = baserightspeed3;
	motor[rearRightMotor] = baserightspeed3; //Move base at a certain speed
	motor[armMotor] = armspeed3; //Move arm at a certain speed
	motor[clawMotor] = -127*clawdirection3; //Move claw at a certain speed
	wait1Msec(time4*1000); //Wait for a certain amount of time
	motor[frontLeftMotor] = 0;
	motor[rearLeftMotor] = 0;
	motor[frontRightMotor] = 0;
	motor[rearRightMotor] = 0;
	motor[armMotor] = 0;
	motor[clawMotor] = 0; //Turn all subsytems in function off
}

//This function moves the base and extension at the same time at a certain speed for a certain amount of time ----------------------------------------------
void moveBaseAndExtension(int baseleftspeed4, int baserightspeed4, int extensionspeed, float time5) //Left side of base, right side of base, extension, time
{
	motor[frontLeftMotor] = baseleftspeed4;
	motor[rearLeftMotor] = baseleftspeed4;
	motor[frontRightMotor] = baserightspeed4;
	motor[rearRightMotor] = baserightspeed4; //Move base at a certain speed
	motor[leftExtendMotor] = extensionspeed;
	motor[rightExtendMotor] = extensionspeed; //Move extension at a certain speed
	wait1Msec(time5*1000); //Wait for a certain amount of time
	motor[frontLeftMotor] = 0;
	motor[rearLeftMotor] = 0;
	motor[frontRightMotor] = 0;
	motor[rearRightMotor] = 0;
	motor[leftExtendMotor] = 0;
	motor[rightExtendMotor] = 0; //Turn all subsystems in function off
}

//This function moves the arm and wrist for a certain amount of time --------------------------------------------------------------------------
void moveArmAndWrist(int armspeed4, int wristspeed, float time6)
{
	motor[armMotor] = armspeed4; //Move arm at a certain speed
	motor[wristMotor] = wristspeed; //Move wrist at a certain speed
	wait1Msec(time6*1000);
	motor[armMotor] = 0;
	motor[wristMotor] = 0; //Turn all subsystems in function off
}

//This function moves the base and wrist for a certain amount of time -------------------------------------------------------------------------
void moveBaseAndWrist(int baseleftspeed5, int baserightspeed5, int wristspeed2, float time7)
{
	motor[frontLeftMotor] = baseleftspeed5;
	motor[rearLeftMotor] = baseleftspeed5;
	motor[frontRightMotor] = baserightspeed5;
	motor[rearRightMotor] = baserightspeed5; //Move base at a certain speed
	motor[wristMotor] = wristspeed2; //Move wrist at a certain speed
	wait1Msec(time7*1000);
	motor[frontLeftMotor] = 0;
	motor[rearLeftMotor] = 0;
	motor[frontRightMotor] = 0;
	motor[rearRightMotor] = 0;
	motor[wristMotor] = 0; //Turn all subsystems in function off
}

//This function moves the base, arm and wrist for a certain amount of time --------------------------------------------------------------------
void moveBaseArmAndWrist(int baseleftspeed6, int baserightspeed6, int armspeed5, int wristspeed3, float time8)
{
	motor[frontLeftMotor] = baseleftspeed6;
	motor[rearLeftMotor] = baseleftspeed6;
	motor[frontRightMotor] = baserightspeed6;
	motor[rearRightMotor] = baserightspeed6; //Move base at a certain speed
	motor[armMotor] = armspeed5; //Move arm at a certain speed
	motor[wristMotor] = wristspeed3; //Move wrist at a certain speed
	wait1Msec(time8*1000);
	motor[frontLeftMotor] = 0;
	motor[rearLeftMotor] = 0;
	motor[frontRightMotor] = 0;
	motor[rearRightMotor] = 0;
	motor[armMotor] = 0;
	motor[wristMotor] = 0; //Turn all subsystems off
}

//This function moves the base, claw, arm, and wrist for a certain amount of time -------------------------------------------------------------
void moveBaseArmClawAndWrist(int baseleftspeed7, int baserightspeed7, int armspeed6, int clawdirection4, int wristspeed4, float time9)
{
	motor[frontLeftMotor] = baseleftspeed7;
	motor[rearLeftMotor] = baseleftspeed7;
	motor[frontRightMotor] = baserightspeed7;
	motor[rearRightMotor] = baserightspeed7; //Move base at a certain speed
	motor[armMotor] = armspeed6; //Move arm at a certain speed
	motor[clawMotor] = -127*clawdirection4; //Move claw at a certain speed
	motor[wristMotor] = wristspeed4; //Move wrist at a certain speed
	wait1Msec(time9*1000);
	motor[frontLeftMotor] = 0;
	motor[rearLeftMotor] = 0;
	motor[frontRightMotor] = 0;
	motor[rearRightMotor] = 0;
	motor[armMotor] = 0;
	motor[clawMotor] = 0;
	motor[wristMotor] = 0; //Turn all subsystems off
}

//This function moves the base, extension, claw, and wrist for a certain amount of time ------------------------------------------------------------
void moveBaseExtensionClawAndWrist (int baseleftspeed8, int baserightspeed8, int extensionspeed2, int clawdirection5, int wristspeed5, float time11)
{
	motor[frontLeftMotor] = baseleftspeed8;
	motor[rearLeftMotor] = baseleftspeed8;
	motor[frontRightMotor] = baserightspeed8;
	motor[rearRightMotor] = baserightspeed8; //Move base at a certain speed
	motor[leftExtendMotor] = extensionspeed2;
	motor[rightExtendMotor] = extensionspeed2; //Move extension at a certain speed
	motor[clawMotor] = -127*clawdirection5; //Move claw at a certain speed
	motor[wristMotor] = wristspeed5; //Move wrist at a certain speed
	wait1Msec(time11*1000);
	motor[frontLeftMotor] = 0;
	motor[rearLeftMotor] = 0;
	motor[frontRightMotor] = 0;
	motor[rearRightMotor] = 0;
	motor[leftExtendMotor] = 0;
	motor[rightExtendMotor] = 0;
	motor[clawMotor] = 0;
	motor[wristMotor] = 0; //Turn all subsystems off
}

//This function moves the base, arm, extension, claw, and wrist for a certain amount of time -------------------------------------------------------------------------
void moveBaseArmExtensionClawAndWrist (int baseleftspeed9, int baserightspeed9, int armspeed7, int extensionspeed3, int clawdirection6, int wristspeed6, float time12)
{
	motor[frontLeftMotor] = baseleftspeed9;
	motor[rearLeftMotor] = baseleftspeed9;
	motor[frontRightMotor] = baserightspeed9;
	motor[rearRightMotor] = baserightspeed9; //Move base at a certain speed
	motor[armMotor] = armspeed7; //Move arm at a certain speed
	motor[leftExtendMotor] = extensionspeed3;
	motor[rightExtendMotor] = extensionspeed3; //Move extension at a certain speed
	motor[clawMotor] = -127*clawdirection6; //Move claw at a certain speed
	motor[wristMotor] = wristspeed6; //Move wrist at a certain speed
	wait1Msec(time12*1000);
	motor[frontLeftMotor] = 0;
	motor[rearLeftMotor] = 0;
	motor[frontRightMotor] = 0;
	motor[rearRightMotor] = 0;
	motor[armMotor] = 0;
	motor[leftExtendMotor] = 0;
	motor[rightExtendMotor] = 0;
	motor[clawMotor] = 0;
	motor[wristMotor] = 0; //Turn all subsystems off
}

//This function moves the base, arm, and extension for a certain amount of time -------------------------------------------------------------------------
void moveBaseArmAndExtension (int baseleftspeed10, int baserightspeed10, int armspeed8, int extensionspeed4, float time13)
{
	motor[frontLeftMotor] = baseleftspeed10;
	motor[rearLeftMotor] = baseleftspeed10;
	motor[frontRightMotor] = baserightspeed10;
	motor[rearRightMotor] = baserightspeed10; //Move base at a certain speed
	motor[armMotor] = armspeed8; //Move arm at a certain speed
	motor[leftExtendMotor] = extensionspeed4;
	motor[rightExtendMotor] = extensionspeed4; //Move extension at a certain speed
	wait1Msec(time13*1000);
	motor[frontLeftMotor] = 0;
	motor[rearLeftMotor] = 0;
	motor[frontRightMotor] = 0;
	motor[rearRightMotor] = 0;
	motor[armMotor] = 0;
	motor[leftExtendMotor] = 0;
	motor[rightExtendMotor] = 0; //Turn all subsystems off
}

//This function moves the base, extension, and claw for a certain amount of time -------------------------------------------------------------------------
void moveBaseExtensionAndClaw (int baseleftspeed11, int baserightspeed11, int extensionspeed5, int clawdirection7, float time14)
{
	motor[frontLeftMotor] = baseleftspeed11;
	motor[rearLeftMotor] = baseleftspeed11;
	motor[frontRightMotor] = baserightspeed11;
	motor[rearRightMotor] = baserightspeed11; //Move base at a certain speed
	motor[leftExtendMotor] = extensionspeed5;
	motor[rightExtendMotor] = extensionspeed5; //Move extension at a certain speed
	motor[clawMotor] = -127*clawdirection7; //Move claw at a certain speed
	wait1Msec(time14*1000);
	motor[frontLeftMotor] = 0;
	motor[rearLeftMotor] = 0;
	motor[frontRightMotor] = 0;
	motor[rearRightMotor] = 0;
	motor[armMotor] = 0;
	motor[leftExtendMotor] = 0;
	motor[rightExtendMotor] = 0; //Turn all subsystems off
}
