#pragma config(StandardModel, "RVW Fantasticbot")
#pragma config(RenamedStdModelSensor, I2C_1, rightEncoder)
#pragma config(RenamedStdModelSensor, I2C_2, leftEncoder)
#pragma config(RenamedStdModelSensor, I2C_3, armEncoder)
#pragma config(RenamedStdModelSensor, I2C_4, extensionEncoder)
#pragma config(RenamedStdModelSensor, I2C_5, wristEncoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//this function moves the wrist motor based off of a certain amount of time
void moveClawForTime(int wristPower, int time)//power to the wrist, time
{
	motor[wristMotor] = wristPower;//move wrist at certain power
	wait1Msec(time);//move wrist for a certain time
}

//This function moves the wrist up until the encoder reaches a certain amount
void moveClawForRotationsUp(int wristEncoderPower, int rotations)
{
	SensorValue[wristEncoder] = 0;//Resets the encoder value on the wrist
	while(SensorValue[wristEncoder] < rotations)
		{
			motor[wristMotor] = wristEncoderPower;//Move the wrist at a certain speed
		}
	motor[wristMotor] = 0;//Stop the wrist
}

//This function moves the wrist down until the encoder reaches a certain amount
void moveClawForRotationsDown(int wristEncoderPowerRev, int negativeRotations)
{
	SensorValue[wristEncoder] = 0;//Resets the encoder value on the wrist
	while(SensorValue[wristEncoder] > -negativeRotations)
		{
			motor[wristMotor] = -wristEncoderPowerRev;//Move the wrist at a certain speed
		}
	motor[wristMotor] = 0;//Stop the wrist
}
