#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    leftLight,      sensorLineFollower)
#pragma config(Sensor, in2,    middleLight,    sensorLineFollower)
#pragma config(Sensor, in3,    rightLight,     sensorLineFollower)
#pragma config(Sensor, in4,    wristPot,       sensorPotentiometer)
#pragma config(Sensor, in6,    gyro,           sensorGyro)
#pragma config(Sensor, dgtl7,  touchSensor,    sensorTouch)
#pragma config(Sensor, dgtl8,  sonarSensor,    sensorSONAR_cm)
#pragma config(Sensor, I2C_1,  rightEncoder,   sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  leftEncoder,    sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_3,  armEncoder,     sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_4,  extensionEncoder, sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_5,  wristEncoder,   sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           frontRightMotor, tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           rearRightMotor, tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_1)
#pragma config(Motor,  port3,           frontLeftMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           rearLeftMotor, tmotorVex393_MC29, openLoop, encoderPort, I2C_2)
#pragma config(Motor,  port6,           clawMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           armMotor,      tmotorVex393_MC29, openLoop, encoderPort, I2C_3)
#pragma config(Motor,  port8,           leftExtendMotor, tmotorVex393_MC29, openLoop, encoderPort, I2C_4)
#pragma config(Motor,  port9,           rightExtendMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          wristMotor,    tmotorVex393_HBridge, openLoop, encoderPort, I2C_5)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


/*
This code is included in all of the files starting with "Main_File_Draft_..."
It consists of all of the functions for the wrist that are needed to run
the fantasticbot properly. These functions are (in order):
- moveClawForTime
- moveClawForRotationsUp
- moveClawForRotationsDown
NOTE: Any function that has to do with the encoders on the wrist (has "Rotations" in the name)
is currently under maintenance. The encoders will not reset properly (still used in main code).
*/


//This function moves the wrist motor for a certain amount of time -----------------------------------------------------------------------------
void moveClawForTime(int wristPower, int time) //Power to the wrist, time
{
	motor[wristMotor] = wristPower; //Move wrist at certain power
	wait1Msec(time); //Move wrist for a certain time
}


//This function moves the wrist up until the encoder reaches a certain amount ------------------------------------------------------------------
void moveClawForRotationsUp(int wristEncoderPower, int rotations)
{
	SensorValue[wristEncoder] = 0; //Reset the encoder value on the wrist
	while(SensorValue[wristEncoder] < rotations) //While the wrist encoder does not read desired value
	{
		motor[wristMotor] = wristEncoderPower; //Move the wrist at a certain speed
	}
	motor[wristMotor] = 0; //Stop the wrist
}

//This function moves the wrist down until the encoder reaches a certain amount ----------------------------------------------------------------
void moveClawForRotationsDown(int wristEncoderPowerRev, int negativeRotations)
{
	SensorValue[wristEncoder] = 0;//Resets the encoder value on the wrist
	while(SensorValue[wristEncoder] > -negativeRotations) //While the wrist encoder does not read desired value
	{
		motor[wristMotor] = -wristEncoderPowerRev;//Move the wrist at a certain speed
	}
	motor[wristMotor] = 0;//Stop the wrist
}
